### ISSUE TITLE
使用unocss后部分样式异常

### ISSUE THREAD

**Issue by Octopus-Xidos** [xingyuv/vue-vben-admin#2]
测试commit: chore: unocss
对比commit: chore: release 1.0.3

首页包括主页的部分样式会发生变化
1.登录页在分辨率w:1279时,响应式样式丢失了
![unocss登录页-w1280](https://user-images.githubusercontent.com/54504278/227828476-47c6be54-5502-45ab-9495-bd6c2c2150f6.png)
![unocss登录页-w1279](https://user-images.githubusercontent.com/54504278/227828414-df77ec5a-985b-4eae-828d-e006be1cbed3.png)

2.部分图标会被span.anticon:not(.app-iconify)修改样式
![unocss-图标样式](https://user-images.githubusercontent.com/54504278/227829367-380bab2e-aa02-4f49-ad31-077298f34848.png)

**Comment by Octopus-Xidos** [comment]
1.首次启动项目,登录页在非w:1279分辨率下显示正常,退出登录后也会不显示左侧图片及描述
2.图标的把span.anticon:not(.app-iconify)这个样式注掉了就会正常,暂时没发现其他图标会错位

**Comment by xingyuv** [comment]
试一下应该是可以了，unocss配置的问题，还是不太熟悉

**Comment by NEWDSA** [comment]
问题依然存在需要注释掉
.w-full{width:100%;}
